### ISSUE TITLE
Support searching by date and time

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/search#27]
The App Engine search API has a date field, but [it ignores the time portion of a date/time instance][1].

I think we could kind of implement proper date/time support by storing unix timestamps in a number field. The number field has a maximum value of 2,147,483,647 so we wouldn't be able to represent any date past 19 January 2038.

    >>> datetime.datetime.fromtimestamp(2147483647)
    datetime.datetime(2038, 1, 19, 3, 14, 7) 

But still pretty useful!

When indexing a Python datetime, the value would be converted to a timestamp. When searching for documents using a datetime, we would mostly likely want a way to query against the relevant indexed field, which I guess is the `.filter(field__lt=..)` stuff.

Not sure what is going to be required to handle the conversion automatically when searching. Otherwise it will be up to the calling code to construct a meaningful query themselves.

[1]: https://cloud.google.com/appengine/docs/python/search/#Python_Special_treatment_of_string_and_date_fields

**Comment by nealedj** [comment]
I like this. I'm guessing that the search API removes times from datetimes during tokenization for performance reasons. It'd be useful to be able to get around this when necessary.

To increase the range of times available and take us to 2106 we could use (timestamp - 2147483646):

- `-2147483647` (`None`)
- `-2147483646` == `1970-01-01:00:00:00` (min)
- `2147483646` == `2106-02-07:06:28:13` (max)

I think all of this logic could be encompassed in a new `DateTimeField`.

**Comment by davidwtbuxton** [comment]
That would be kind of weird shifting all the timestamps by 68 years, but I see it would work. Would it be worth the confusion?

My specific use case was for an app where we are searching for records by the creation date, and we want to consider the user's timezone. I don't expect the app will need to deal with dates beyond 2038 (because it is unlikely to live that long).

**Comment by nealedj** [comment]
True, it probably wouldn't be worth the extra effort and potential for unnecessary debugging confusion.

I might get around to this later unless you were going to pick it up?

**Comment by davidwtbuxton** [comment]
Depends what you mean by later. I was thinking of having a go tomorrow, depending on things.

**Comment by davidwtbuxton** [comment]
What should we do about handling Python datetimes with or without tzinfo? Feels wrong to insist that values either must all be aware or must all be naive. If we allowed setting either, what should we return?

I was thinking we could have each field instance check for values. Each instance switches to either requiring or forbidding tzinfo depending on what was set first.

But the problem with that is what if we start converting search results, before the app has set any datetime values? What do we choose when converting a timestamp and the app hasn't indicated which it prefers?

Maybe we could have 2 classes, DateTimeField, NaiveDateTimeField, and they require all values to be aware / naive appropriately.
